### ISSUE TITLE
Remove linter related code from other project

### ISSUE THREAD

**Issue by HouCoder** [juwai/juwai-lint-cfg#20]
I reconsidered the current situation and nobody likes spreading linter and config files in every project, since stylelint, eslint, jscs(was eaten by eslint project, we should drop it in the near future) already offered great global command line interface tools:

1. [stylelint](https://www.npmjs.com/package/stylelint).
1. [eslint](https://www.npmjs.com/package/eslint#global-installation-and-usage).
1. [jscs](https://www.npmjs.com/package/jscs).

We can install them globally, put all config files into one place - your home folder, centralizing configs makes maintenance much easier.

In each project, we can drop the `juwai-lint-cfg` npm package in package.json and grunt/gulp/webpack linter plugins, just put `eslint  EXAMPLE`, `stylelint EXAMPLE` in your git hook pre-commit script.

**Comment by arkhi** [comment]
I have a few questions after reading the issue, let me know if I misunderstood something:

1. Can we list the arguments against having the rc files in each repository?
1. When you write `We can install them globally`, is that every developer’s responsibility to do so? How do we ensure people have the latest revisions of the modules and configuration in their repository?
1. How do we lint the code with Travis-CI (or any other continuous integration tool)?

**Comment by HouCoder** [comment]
Thanks for reply.

---
> Can we list the arguments against having the rc files in each repository?

The code style should be consistent across all the company projects(ideally), the the easiest way to achieve that is put config file into one centralized place, so that we can more easily maintain it, for instance if we made an update for `.stylelintrc` config file in this repo and need update it for each project, assuming each project has it's own `.stylelintrc`, how many PRs we gonna have for updating them? but with centralized `.stylelintrc`, developer just need update one `.stylelintrc` in their home folder, and updating could be done by one command `$ curl -o ~/.stylelintrc https://raw.githubusercontent.com/juwai/juwai-lint-cfg/master/.stylelintrc`.

---
> When you write We can install them globally, is that every developer’s responsibility to do so? 

No, it's not, if you are not a front-end developer, and don't have ESLint/stylelint/jscs installed, the git hook will skip linting front-end files in your local.

---
> How do we lint the code with Travis-CI (or any other continuous integration tool)?

Basic it's same as before.

1. Download latest linter configurations from this repo.

This could be done with a simple curl commands, e.g:

Get the latest stylelintrc config: `$ curl -o ~/.stylelintrc https://raw.githubusercontent.com/juwai/juwai-lint-cfg/master/.stylelintrc`

2. Install linters

`$ npm install -g stylelint`

3. Lint it!

`$ stylelint public/assets/css`

---
> How do we ensure people have the latest revisions of the modules and configuration in their repository?

Previous answer has maintained that Travis-CI  always downloads the latest configs/tools, if your local configs/tools were out of date, you probably won't pass the CI check, that ensures/forces you update your local configs/tools, with centralized configs and globalized linting tools, you don't need touch any project related code, pretty simple.

**Comment by HouCoder** [comment]
Closing this PR, achieved this purpose in https://github.com/juwai/eslint-config-juwai and https://github.com/juwai/stylelint-config-juwai
